### ISSUE TITLE
ePub output

### ISSUE THREAD

**Issue by chrisvire** [ubsicap/usfm#144]
Could a GitHub action be added that would convert the html files into an ePub document output?

**Comment by jamespostsil** [comment]
This would be of interest to Paratext users as well.

**Comment by chrisvire** [comment]
There is an `epub` target in the `Makefile` and `make.bat`. I tried to `make epub` on Windows, macOS, and Linux with no luck.  There is no documentation on what to install. I installed what I could figure out, but I still ended up with this error:

On Mac:
```
  File "/usr/local/Cellar/sphinx-doc/7.0.0/libexec/lib/python3.11/site-packages/sphinx/config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hubbard/codereview/usfm/docs/conf.py", line 125, in <module>
    import sphinx_rtd_theme
ModuleNotFoundError: No module named 'sphinx_rtd_theme'
```

On Windows:
```
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\sphinx\config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CHubbard\src\usfm\docs\conf.py", line 125, in <module>
    import sphinx_rtd_theme
ModuleNotFoundError: No module named 'sphinx_rtd_theme'
```

**Comment by jamespostsil** [comment]
Great to know you're working on improving the docs! I noticed you can
search for "\f" and it comes up with a number of results, which IS a great
improvement. Plus the dynamically updating feature (can't remember what
it's called) that searches as you type.

Do you have an estimate for when the new version will be available? It
doesn't seem worth trying to finagle a PDF out of a system that will be
replaced soon.

Thanks for letting us know,

James

--

*James Post*


*Language Technology Consultant*
SIL International
***@***.***

**Comment by klassenjm** [comment]
Personally, I would not try very hard to get a PDF output. I've tried, including going via a LaTeX build first. If someone requires an offline copy right now, I would just grab a copy of the HTML docs in this zip file, unpack, and browse locally.

https://markups.paratext.org/wp-content/uploads/2020/04/usfm-docs_3.0.1.zip

Estimate: A couple of months? Part of the process happening now is not only documentation but developing a grammar which clearly defines valid USFM and USX, independent of a particular editor. It's part time work for a few people, but it is moving along steadily.
